# Generated by Django 4.1 on 2022-08-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_app', '0002_book_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ProfileImage',
            field=models.FileField(default='', upload_to='profiles/'),
        ),
    ]
